spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
        reset-enable: false
      web-stat-filter:
        enabled: true
        exclusions: '*.html,*.js,*.css,*.json'
        url-pattern: /*
      aop-patterns: org.spring.demo.*
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
  jdbc:
    template:
      query-timeout: 3
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: always